created event-schema scaffold
gbrlmrllo/chatops_builder_api pull request #14
Opened 2020-05-03 01:42 UTC by anyelopetit

## Issue Ref #[11](https://github.com/gbrlmrllo/chatops_builder_api/issues/11])

### Description
An EventSchema establish a default config for each event in an App so that each external event will be processed based on the config.

## Columns

```ruby
name: # Name that must be unique.
description: # A short description
schema: # The payload format to be received will be established,
                # this will allow validating the payload in a certain way. 
creator: # User who creates the event.
app: # Associated app.
```

## Schema

It will be divided into two sections

```{ data: [...], recipients: [...] }```

```ruby
data: [...] # It must be a column name list
recipients: [...]  # It must be a column name list
```

## Request's example

Let's imagine that we want to send a notification to several users, these users are in charge of processing a purchase order.

```javascript
curl --location --request POST 'http://localhost:3000/api/v1/apps/:id/event_schemas' \
--header 'Content-Type: application/json' \
--data-raw '{ 
  "name": "created_order",
  "description": "Notification for admins",
  "schema": {
    "data": ["order_id", "order_name", "order_price", "product_image"]
    "recipients": ["email", "user_name"]
  }
}'
```

2020-05-03 23:23 UTC, gbrlmrllo requested changes
@anyelopetit Excellent job 💯everything looks fine, code wise. 🥇 

I left a few minor comments.  💬

2020-05-03 23:23 UTC, gbrlmrllo commented on spec/controllers/v1/apps_controller_spec.rb
>        it "401 - Unauthorized" do
👍 thanks for this fix.

2020-05-03 23:23 UTC, gbrlmrllo commented on spec/controllers/v1/apps_controller_spec.rb
> +        get :show, params: { id: "id" }
👍

2020-05-03 23:23 UTC, gbrlmrllo commented on app/models/event_schema.rb
> +  belongs_to :app
It should be required.

```suggestion
  belongs_to :app, optional: false
```

2020-05-03 23:23 UTC, gbrlmrllo commented on app/models/event_schema.rb
> +  scope :schema_structure, -> { { data: [], recipient: [] } }
Scope methods are generally used to define queries, it is confusing to see it and that it does not implement an ActiveRecord query, it is preferable to declare this as a class method.

```ruby 
def self.schema_structure
   { data: [], recipient: [] }
end
```

Should also add a spec for this method.

2020-05-03 23:23 UTC, gbrlmrllo commented on app/controllers/v1/event_schemas_controller.rb
> +    # GET api/v1/apps/1/event_schemas
The comment is a little more informative if we know what is the key of the id.

```# GET api/v1/apps/:app_id/event_schemas```

2020-05-03 23:23 UTC, gbrlmrllo commented on app/models/app.rb
> +  has_many :event_schemas, dependent: :destroy
Can you add a spec for this in `model/app_spec.rb`?

2020-05-03 23:58 UTC, anyelopetit commented on spec/controllers/v1/apps_controller_spec.rb
>        it "401 - Unauthorized" do
you're welcome!

2020-05-04 14:24 UTC, gbrlmrllo requested changes

2020-05-04 14:24 UTC, gbrlmrllo commented on spec/models/event_schema_spec.rb
> +    it "is a Hash" do
```suggestion
    it "returns a hash" do
```

2020-05-04 14:24 UTC, gbrlmrllo commented on spec/models/event_schema_spec.rb
> +    it "has only two keys" do
This test and the one below are redundant, you can remove this one.

2020-05-04 14:33 UTC, merged